version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: cloud-services-web
    expose:
      - "5000"
    depends_on:
      - db
      - redis
    environment:
      - POSTGRES_HOST=db
      - REDIS_HOST=redis
    networks:
    - default
  
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=flask_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
    - default
  
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
    - default
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    restart: always
    depends_on:
      - web
      - prometheus
      - grafana
    networks:
    - default
  
  certbot:
    image: certbot/certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    networks:
    - default
  
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9089:9089"
    command:
      - '--web.listen-address=:9089'
    networks:
    - default

  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"
    networks:
    - default
  
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
    - default
    
volumes:
  postgres_data:

networks:
  default:
    name: cloud-services_default
    external: true

#   prometheus:
#     image: prom/prometheus:latest
#     volumes:
#       - ./prometheus.yml:/etc/prometheus/prometheus.yml
#     ports:
#       - "9090:9090"

#   node-exporter:
#     image: prom/node-exporter:latest
#     ports:
#       - "9100:9100"
  
#   grafana:
#     image: grafana/grafana:latest
#     ports:
#       - "3000:3000"
#     environment:
#       - GF_SECURITY_ADMIN_USER=admin
#       - GF_SECURITY_ADMIN_PASSWORD=admin
#     depends_on:
#       - prometheus
  
#   elasticsearch:
#     image: elasticsearch:8.16.0
#     environment:
#       - discovery.type=single-node
#       - xpack.security.enabled=false
#     ports:
#       - "9200:9200"
#     volumes:
#       - esdata:/usr/share/elasticsearch/data

#   logstash:
#     image: logstash:8.16.0
#     volumes:
#       - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
#     ports:
#       - "5000:5000"
#     depends_on:
#       - elasticsearch

#   kibana:
#     image: kibana:8.16.0
#     ports: 
#       - "5601:5601"
#     depends_on:
#       - elasticsearch

# volumes:
#   esdata: