version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    expose:
      - "5000"
    ports:
      - "5000"
    deploy:
      replicas: 3
  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web

  certbot:
    image: certbot/certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
