global:
  scrape_interval: 15s

web:
  external-url: 'https://breez-domain.ru/prometheus'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9089']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'flask_app'
    metrics_path: /metrics
    static_configs:
      - targets: ['web:5000']