name: Deploy to Server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          if_key_exists: replace
          
      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=accept-new root@147.45.173.136 "docker pull breez97/flask-app:latest && docker-compose up -d"