name: Flask CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and run tests
        run: |
          docker build -t flask-test-app -f Dockerfile.test .
          docker run flask-test-app
